services:
  backend:
    container_name: rrc-backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - internal_data:/internal_data
      - hf_cache:/home/app/.cache/huggingface
    environment:
      - RRC_DATA_ROOT=/internal_data
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - RRC_API_URL=/api
    container_name: rrc-frontend
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
      - frontend
    restart: unless-stopped

volumes:
  internal_data:
    driver: local
  hf_cache:
    driver: local
