// @ts-nocheck
// This file is auto-generated by @hey-api/openapi-ts

import type { Options } from "@hey-api/client-fetch";
import { type UseMutationOptions, queryOptions } from "@tanstack/react-query";
import { DefaultService, client } from "../services.gen";
import type {
  CreateProxyPatternData,
  CreateProxyPatternError,
  CreateProxyPatternResponse,
  DeleteProxyPatternData,
  DeleteProxyPatternError,
  DeleteProxyPatternResponse,
  ReadProxyPatternData,
  UpdateProxyPatternData,
  UpdateProxyPatternError,
  UpdateProxyPatternResponse,
} from "../types.gen";

type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};

export const listProxyPatternsQueryKey = (options?: Options) => [
  createQueryKey("listProxyPatterns", options),
];

export const listProxyPatternsOptions = (options?: Options) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await DefaultService.listProxyPatterns({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listProxyPatternsQueryKey(options),
  });
};

export const createProxyPatternQueryKey = (
  options: Options<CreateProxyPatternData>,
) => [createQueryKey("createProxyPattern", options)];

export const createProxyPatternOptions = (
  options: Options<CreateProxyPatternData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await DefaultService.createProxyPattern({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: createProxyPatternQueryKey(options),
  });
};

export const createProxyPatternMutation = (
  options?: Partial<Options<CreateProxyPatternData>>,
) => {
  const mutationOptions: UseMutationOptions<
    CreateProxyPatternResponse,
    CreateProxyPatternError,
    Options<CreateProxyPatternData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await DefaultService.createProxyPattern({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const readProxyPatternQueryKey = (
  options: Options<ReadProxyPatternData>,
) => [createQueryKey("readProxyPattern", options)];

export const readProxyPatternOptions = (
  options: Options<ReadProxyPatternData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await DefaultService.readProxyPattern({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: readProxyPatternQueryKey(options),
  });
};

export const updateProxyPatternMutation = (
  options?: Partial<Options<UpdateProxyPatternData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UpdateProxyPatternResponse,
    UpdateProxyPatternError,
    Options<UpdateProxyPatternData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await DefaultService.updateProxyPattern({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const deleteProxyPatternMutation = (
  options?: Partial<Options<DeleteProxyPatternData>>,
) => {
  const mutationOptions: UseMutationOptions<
    DeleteProxyPatternResponse,
    DeleteProxyPatternError,
    Options<DeleteProxyPatternData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await DefaultService.deleteProxyPattern({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
